config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [] do
    resources :rooms, only: [:index, :show]
  end
  resources :messages, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates_presence_of :content

  def template
    ApplicationController.renderer.render partial: 'messages/message', locals: { message: self }
  end
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :user_rooms, dependent: :destroy
    has_many :users, through: :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_rooms, dependent: :destroy
    has_many :rooms, through: :user_rooms
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.create!(message_params)
    @room = Room.find_by(id: message_params[:room_id])
    RoomChannel.broadcast_to(@room, message: @message.template)
  end

  private
    def message_params
      params.require(:message).permit(:content, :room_id, :user_id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_user, only: [:index, :show]

  def index
    @rooms = @user.rooms.all
  end

  def show
    @room = @user.rooms.find(params[:id])
    @messages = @room.messages.all
    @message = @room.messages.build
  end

  private
    def set_user
      @user = User.find(params[:user_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MultipleChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<p>
    <strong><%= message.user.name %></strong>
    > <%= message.content %>
</p>

app/views/messages/create.js.erb
document.getElementById("message_content").value = ''

app/views/rooms/index.html.erb
<h1>Chat Rooms</h1>

<ul>
    <% @rooms.each do |room| %>
        <li><%= link_to room.name, user_room_path(@user,room) %></li>
    <% end %>
</ul>

app/views/rooms/show.html.erb
<h1><%= @room.name %></h1>
<div id="data" data-room-id="<%= @room.id %>" data-user-id="<%= @user.id %>"></div>

<div id="container">
    <%= render @messages %>
</div>

<%= form_with(model: @message, html:{name: "myform"}) do |f| %>
    <%= f.text_field :content %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.hidden_field :room_id, value: @room.id %>
    <%= f.submit '送信' %>
<% end %>

<%= link_to 'Back', user_rooms_path(@user) %>